version = "1.3.0"
builder = "spa"

[template_settings]
background-color = "#121414"
text-color = "#c7cfcc"
custom-color = "#f3a833"
autoreload = "1"
highlight-color = "#73bed3"
accent-color = "#2D4566"
